### PR TITLE
Fix: Table-Exists if Server returns 204

### PR DESCRIPTION
**Pull request by c-thiel**
Fixes https://github.com/apache/iceberg-python/issues/735

### CODE REVIEW

**Review by amogh-jahagirdar — COMMENTED** [review]
good catch @c-thiel and thanks for fixing! Change looks good, but if we could add a test similar to https://github.com/apache/iceberg-python/blob/20b7b5339a1a0ab59d884c7d042c4bc96a166b11/tests/catalog/test_rest.py#L666 that would be great.

**Comment by c-thiel** [comment]
@amogh-jahagirdar I added the test. Let me know if something else is missing!

**Review by amogh-jahagirdar — APPROVED** [review]
The change looks good, I'll wait for @HonahX @Fokko in case they have any comments before merging!

**Review by HonahX — APPROVED** [review]
LGTM! Thanks for fixing this!

**Review by Fokko — APPROVED** [review]
Thanks @c-thiel for fixing this 🙌! Thanks @HonahX and @amogh-jahagirdar for the review 🚀

**Pull request merged**
