### PR TITLE
Support of before and after actions in preorderschema traversal

### PR DESCRIPTION
**Pull request by MehulBatra**
Add support to perform an action before and after schema traversal in preorder fashion for schema 
for object: structtype, maptype & listtype
Linked: https://github.com/apache/iceberg-python/issues/32

### CODE REVIEW

**Comment by rdblue** [comment]
I don't think that this is necessary and I think it also breaks future uses of the visitor.

Despite the name, the visitor this updates doesn't actually perform pre-order traversal. It creates futures that can be called to produce the result of further processing. In Java, we call this the "custom order" visitor because you can use it for any order you want by calling the future at a different point.

This PR changes to actual pre-order traversal. That's fine, but it means that you can't actually customize as much.

**Comment by rdblue** [comment]
Maybe it's me, but I don't understand the value of adding before and after callbacks to this visitor. A node's children are traversed when the future is called and that allows you to do whatever you want before and after further schema traversal. I think it makes more sense to consolidate the logic in the usual methods rather than use callbacks in this case.

**Comment by MehulBatra** [comment]
> Maybe it's me, but I don't understand the value of adding before and after callbacks to this visitor. A node's children are traversed when the future is called and that allows you to do whatever you want before and after further schema traversal. I think it makes more sense to consolidate the logic in the usual methods rather than use callbacks in this case.

It's still half baked I am working on it, but thanks for the feedback, will that into consideration.

**Comment by Fokko** [comment]
This was suggested here: https://github.com/apache/iceberg/pull/7831/files#r1285259053 I'll leave it up to @rdblue to decide if he thinks this is valuable.

**Comment by Fokko** [comment]
Let's keep it as is, and close this for now.

**Pull request closed without merging**
