### PR TITLE
Remove hard-coded release version

### PR DESCRIPTION
**Pull request by danielcweeks**
Improves the verification steps to:
- not include a hard coded version (could result in users verifying the wrong version)
- use distinct paths so that the verification directory isn't reused across versions

### CODE REVIEW

**Review by HonahX — COMMENTED** [review]
Shall we also remove the hard-coded release version here?
https://github.com/apache/iceberg-python/blob/188e2c4d63f294fc55351916fb8d62a5a4401d3d/mkdocs/docs/verify-release.md?plain=1#L70-L73
```sh
export PYICEBERG_VERSION_WITHOUT_RC=${PYICEBERG_VERSION/rc?/}
tar xzf pyiceberg-${PYICEBERG_VERSION_WITHOUT_RC}.tar.gz
cd pyiceberg-${PYICEBERG_VERSION_WITHOUT_RC}
```

**Comment by danielcweeks** [comment]
Nice catch @HonahX!

**Review by Fokko — APPROVED** [review]
Thanks for fixing this @danielcweeks! 🙌  And thanks @HonahX for the review 🚀

**Review by HonahX — APPROVED** [review]
Thanks for working on this!@danielcweeks

**Pull request merged**
