### PR TITLE
docs: Remove feature support page

### PR DESCRIPTION
**Pull request by Fokko**
With the 0.6.0 release we'll check the last box, and we have feature parity with Java according to this table. I would prefer creating tickets on Github to point out the gaps rather than this page.

### CODE REVIEW

**Review by amogh-jahagirdar — APPROVED** [review]
Agree, at this point in the development of the project I think it makes more sense for us to track gaps in the Github issues rather than a page.

**Review by syun64 — APPROVED** [review]
What a milestone!

**Review by HonahX — APPROVED** [review]
LGTM!

**Comment by Fokko** [comment]
Thanks everyone for the quick review 🙌

**Pull request merged**
