### PR TITLE
Improve test_version_format() error message for version mismatches 

### LINKED ISSUE #949: [documentation] library version upgrade fails `test_version_format`
### Feature Request / Improvement

When Pyiceberg upgrades its version, such as now from `0.6.1` -> `0.7.0`. The local repo will fail `test_version_format` until the library is reinstalled with the new version.

Add explanation to [`test_version_format`](https://github.com/apache/iceberg-python/blob/d8bc1ca9af7957ce4d4db99a52c701ac75db7688/tests/test_version.py#L21) error message that the failure can be due to the Pyiceberg library version bump and possible solution such as to rerun `make install`.

```
================================================================== FAILURES ==================================================================
____________________________________________________________ test_version_format _____________________________________________________________

    def test_version_format() -> None:
        from importlib import metadata
    
        installed_version = metadata.version("pyiceberg")
    
>       assert (
            __version__ == installed_version
        ), f"{__version__} <> {installed_version}, the installed version does not match with the current codebase"
E       AssertionError: 0.7.0 <> 0.6.1, the installed version does not match with the current codebase
E       assert '0.7.0' == '0.6.1'
E         - 0.6.1
E         + 0.7.0

tests/test_version.py:26: AssertionError
```

### PR DESCRIPTION
**Pull request by laksh-krishna-sharma**
## What Does This PR Address?
Enhances the test_version_format() Error Message for Version Mismatches.

Fixes #949

## Description
This PR enhances the test_version_format() function in tests/test_version.py by updating the error message to be more informative. The new message provides clearer guidance on resolving version mismatch issues, including a suggestion to rerun make install if needed.

### CODE REVIEW

**Comment by laksh-krishna-sharma** [comment]
image

 @kevinjqliu sir , Thanks for your feedback.

I've resolved the linter issue as indicated. I created a new PR due to some issues on my machine. I apologize for any inconvenience this may have caused. Please review the updated changes.

**Comment by kevinjqliu** [comment]
Looks like theres another lint issue. Can you run `make lint` again?

**Comment by laksh-krishna-sharma** [comment]
Sure, I'll run make lint again.

**Comment by laksh-krishna-sharma** [comment]
image
Sir, please guide me about what I have to do to resolve this.

**Comment by kevinjqliu** [comment]
can you try running `make install` first? 
did you follow these steps? https://py.iceberg.apache.org/contributing/

I'm not very familiar with Windows environment

**Comment by laksh-krishna-sharma** [comment]
Yes, I followed all the steps mentioned in the contribution guide and ran `make install` and `make lint`. I also resolved the issues that came up. Please review the update.

**Comment by laksh-krishna-sharma** [comment]
image
While running `make install`, I encountered the error shown in the above screenshot.

image
image
While running `make lint`, I encountered the error shown in the above screenshot.

**Comment by kevinjqliu** [comment]
That's odd, it might be due to the specific Python version on Windows. I found a similar issue https://github.com/python-poetry/poetry/issues/3894#issuecomment-1130034154

**Comment by kevinjqliu** [comment]
I can run `make lint` for this branch

**Review by kevinjqliu — APPROVED** [review]
LGTM!

**Comment by kevinjqliu** [comment]
Thanks for the contribution, @laksh-krishna-sharma

**Comment by laksh-krishna-sharma** [comment]
Thank you, @kevinjqliu  I am grateful for the opportunity to contribute and for your patient guidance. I would like to work more under your guidance in this repository. I am looking to contribute more and learn from you. This being my second contribution, it has been an amazing experience, and I have learned a lot. I am excited to continue contributing and learning.

**Pull request merged**
