### PR TITLE
Add install extra for sqlite

### PR DESCRIPTION
**Pull request by kevinjqliu**
[Issue #285](https://github.com/apache/iceberg-python/issues/285)

### CODE REVIEW

**Review by Fokko — APPROVED** [review]

**Comment by Fokko** [comment]
@kevinjqliu Thanks for working on this!

**Comment by kevinjqliu** [comment]
@Fokko np. I had to rebase and regenerate the lock file

**Comment by Fokko** [comment]
@kevinjqliu There is no upper bound constraint on Ray, and therefore it is bumped to the latest version, which is not compatible for some reason. I've created https://github.com/apache/iceberg-python/pull/298 to fix this for now. If you run revert the changes in `poetry.lock` and run `poetry lock --no-update` then it will not update Ray to the latest version.

**Comment by kevinjqliu** [comment]
@Fokko thanks, I just ran `poetry lock --no-update`

**Comment by Fokko** [comment]
Thanks @kevinjqliu for picking this up 🙌

**Pull request merged**
