### PR TITLE
Github: Add 0.6.1 to issue template

### PR DESCRIPTION
**Pull request by Fokko**

### CODE REVIEW

**Review by syun64 — APPROVED** [review]

**Review by kevinjqliu — COMMENTED** [review]
is there a way to add this task to the release process?

**Comment by Fokko** [comment]
@kevinjqliu Great point, I've added it to the doc, LMKWYT

**Review by kevinjqliu — APPROVED** [review]
lgtm!

**Review by HonahX — APPROVED** [review]

**Comment by HonahX** [comment]
Sorry for being late. @Fokko Thanks for adding this! @syun64 @kevinjqliu Thanks for reviewing!

**Pull request merged**
