### PR TITLE
Use ArrowScan.to_table to replace project_table

### PR DESCRIPTION
**Pull request by JE-Chen**
PR #1119 
- Use ArrowScan.to_table to replace project_table in these files: 
  - pyiceberg\table\__init__.py
  - pyiceberg\io\pyarrow.py
  - pyiceberg\test_pyarrow.py

### CODE REVIEW

**Comment by sungwy** [comment]
Hi @JE-Chen thank you for putting together this PR! It looks like these were missed in the initial refactoring. Running the CI now.

**Comment by JE-Chen** [comment]
Hi @sungwy I have already fixed the problem that ruff found.

**Review by kevinjqliu — COMMENTED** [review]
Thanks for the contribution! 

Looks like this captures all the `project_table` usage https://github.com/search?q=repo%3Aapache%2Ficeberg-python%20project_table&type=code

Let's double check the log for `make test` and `make test-integration` to make sure there's no deprecation warnings related to `project_table`

**Comment by JE-Chen** [comment]
`make test` log:

<details>

```
======================================================================================== warnings summary ========================================================================================
tests/catalog/test_base.py: 17 warnings
tests/catalog/test_dynamodb.py: 22 warnings
tests/catalog/test_glue.py: 29 warnings
tests/catalog/test_hive.py: 12 warnings
tests/catalog/test_rest.py: 18 warnings
tests/catalog/test_sql.py: 499 warnings
  /home/jeffrey/desktop/GItHub_Project/iceberg-python/pyiceberg/utils/deprecated.py:51: DeprecationWarning: Deprecated in 0.8.0, will be removed in 0.9.0. Table.identifier property is deprecated. Pase use Table.name() function instead.
    _deprecation_warning(message)

tests/catalog/test_base.py: 5 warnings
tests/catalog/test_dynamodb.py: 5 warnings
tests/catalog/test_glue.py: 13 warnings
tests/catalog/test_hive.py: 8 warnings
tests/catalog/test_rest.py: 4 warnings
tests/catalog/test_sql.py: 690 warnings
  /home/jeffrey/desktop/GItHub_Project/iceberg-python/pyiceberg/utils/deprecated.py:51: DeprecationWarning: Deprecated in 0.8.0, will be removed in 0.9.0. Support for parsing catalog level identifi in Catalog identifiers is deprecated. Please refer to the table using only its namespace and its table name.
    _deprecation_warning(message)

tests/catalog/test_dynamodb.py::test_passing_provided_profile
tests/catalog/test_dynamodb.py::test_passing_glue_session_properties
tests/catalog/test_dynamodb.py::test_passing_unified_session_properties_to_dynamodb
tests/catalog/test_glue.py::test_passing_profile_name
tests/catalog/test_glue.py::test_passing_glue_session_properties
tests/catalog/test_glue.py::test_passing_unified_session_properties_to_glue
  /home/jeffrey/desktop/GItHub_Project/iceberg-python/pyiceberg/utils/deprecated.py:51: DeprecationWarning: Deprecated in 0.7.0, will be removed in 0.8.0. The property aws_access_key_id is deprecat. Please use properties that start with client., glue., and dynamo. instead
    _deprecation_warning(message)

tests/catalog/test_dynamodb.py::test_passing_provided_profile
tests/catalog/test_dynamodb.py::test_passing_glue_session_properties
tests/catalog/test_dynamodb.py::test_passing_unified_session_properties_to_dynamodb
tests/catalog/test_glue.py::test_passing_profile_name
tests/catalog/test_glue.py::test_passing_glue_session_properties
tests/catalog/test_glue.py::test_passing_unified_session_properties_to_glue
  /home/jeffrey/desktop/GItHub_Project/iceberg-python/pyiceberg/utils/deprecated.py:51: DeprecationWarning: Deprecated in 0.7.0, will be removed in 0.8.0. The property region_name is deprecated. Plse use properties that start with client., glue., and dynamo. instead
    _deprecation_warning(message)

tests/catalog/test_dynamodb.py::test_passing_provided_profile
tests/catalog/test_dynamodb.py::test_passing_glue_session_properties
tests/catalog/test_dynamodb.py::test_passing_unified_session_properties_to_dynamodb
tests/catalog/test_glue.py::test_passing_profile_name
tests/catalog/test_glue.py::test_passing_glue_session_properties
tests/catalog/test_glue.py::test_passing_unified_session_properties_to_glue
  /home/jeffrey/desktop/GItHub_Project/iceberg-python/pyiceberg/utils/deprecated.py:51: DeprecationWarning: Deprecated in 0.7.0, will be removed in 0.8.0. The property aws_secret_access_key is deprated. Please use properties that start with client., glue., and dynamo. instead
    _deprecation_warning(message)

tests/catalog/test_dynamodb.py::test_passing_provided_profile
tests/catalog/test_dynamodb.py::test_passing_glue_session_properties
tests/catalog/test_dynamodb.py::test_passing_unified_session_properties_to_dynamodb
tests/catalog/test_glue.py::test_passing_profile_name
tests/catalog/test_glue.py::test_passing_glue_session_properties
tests/catalog/test_glue.py::test_passing_unified_session_properties_to_glue
  /home/jeffrey/desktop/GItHub_Project/iceberg-python/pyiceberg/utils/deprecated.py:51: DeprecationWarning: Deprecated in 0.7.0, will be removed in 0.8.0. The property aws_session_token is deprecat. Please use properties that start with client., glue., and dynamo. instead
    _deprecation_warning(message)

tests/catalog/test_dynamodb.py::test_passing_glue_session_properties
tests/catalog/test_dynamodb.py::test_passing_unified_session_properties_to_dynamodb
tests/catalog/test_glue.py::test_passing_profile_name
tests/catalog/test_glue.py::test_passing_glue_session_properties
tests/catalog/test_glue.py::test_passing_unified_session_properties_to_glue
  /home/jeffrey/desktop/GItHub_Project/iceberg-python/pyiceberg/utils/deprecated.py:51: DeprecationWarning: Deprecated in 0.7.0, will be removed in 0.8.0. The property profile_name is deprecated. Pase use properties that start with client., glue., and dynamo. instead
    _deprecation_warning(message)

tests/catalog/test_rest.py: 10 warnings
  /home/jeffrey/desktop/GItHub_Project/iceberg-python/pyiceberg/utils/deprecated.py:51: DeprecationWarning: Deprecated in 0.8.0, will be removed in 1.0.0. Iceberg REST client is missing the OAuth2 rver URI configuration and defaults to https://iceberg-test-catalog/oauth/tokens. This automatic fallback will be removed in a future Iceberg release.It is recommended to configure the OAuth2 endpoint using the 'oauth2-server-uri'property to be prepared. This warning will disappear if the OAuth2endpoint is explicitly configured. See https://github.com/apache/iceberg/issues/10537
    _deprecation_warning(message)

tests/catalog/test_rest.py::test_drop_view_invalid_namespace
tests/catalog/test_rest.py::test_drop_view_404
tests/catalog/test_rest.py::test_drop_view_204
  /home/jeffrey/desktop/GItHub_Project/iceberg-python/pyiceberg/utils/deprecated.py:35: DeprecationWarning: Call to identifier_to_tuple_without_catalog, deprecated in 0.8.0, will be removed in 0.9. Support for parsing catalog level identifier in Catalog identifiers is deprecated. Please refer to the table using only its namespace and its table name..
    _deprecation_warning(message)

tests/catalog/test_sql.py: 6 warnings
tests/io/test_pyarrow.py: 23 warnings
  /home/jeffrey/desktop/GItHub_Project/iceberg-python/pyiceberg/utils/deprecated.py:35: DeprecationWarning: Call to project_table, deprecated in 0.8.0, will be removed in 0.9.0. project_table is deecated. Use ArrowScan.to_table instead..
    _deprecation_warning(message)

tests/expressions/test_parser.py::test_is_null
tests/expressions/test_parser.py::test_is_null
tests/expressions/test_parser.py::test_is_null
tests/expressions/test_parser.py::test_is_null
  /home/jeffrey/desktop/GItHub_Project/iceberg-python/pyiceberg/utils/deprecated.py:51: DeprecationWarning: Deprecated in 0.8.0, will be removed in 0.9.0. Parsing expressions with table name is deprecated. Only provide field names in the row_filter.
    _deprecation_warning(message)

tests/table/test_name_mapping.py::test_mapping_lookup_by_name
tests/table/test_name_mapping.py::test_mapping_lookup_by_name
tests/table/test_name_mapping.py::test_mapping_lookup_by_name
tests/table/test_name_mapping.py::test_mapping_lookup_by_name
tests/table/test_name_mapping.py::test_mapping_lookup_by_name
  /home/jeffrey/desktop/GItHub_Project/iceberg-python/pyiceberg/utils/deprecated.py:35: DeprecationWarning: Call to find, deprecated in 0.8.0, will be removed in 0.9.0. Please use `apply_name_mappi` instead.
    _deprecation_warning(message)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
====================================================================== 2791 passed, 849 deselected, 1402 warnings in 39.29s ======================================================================

```

</details>

`make test-integration` have so many error, any ideas?

<details>

```
$ make test-integration
docker compose -f dev/docker-compose-integration.yml kill
WARN[0000] /home/jeffrey/Desktop/GItHub_Project/iceberg-python/dev/docker-compose-integration.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Killing 5/5
 ✔ Container pyiceberg-minio  Killed                                                                                                                                                         0.3s 
 ✔ Container pyiceberg-mc     Killed                                                                                                                                                         0.1s 
 ✔ Container pyiceberg-rest   Killed                                                                                                                                                         0.2s 
 ✔ Container hive             Killed                                                                                                                                                         0.2s 
 ✔ Container pyiceberg-spark  Killed                                                                                                                                                         0.3s 
docker compose -f dev/docker-compose-integration.yml rm -f
WARN[0000] /home/jeffrey/Desktop/GItHub_Project/iceberg-python/dev/docker-compose-integration.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
Going to remove pyiceberg-spark, pyiceberg-mc, pyiceberg-rest, hive, pyiceberg-minio
[+] Removing 5/0
 ✔ Container pyiceberg-minio  Removed                                                                                                                                                        0.0s 
 ✔ Container pyiceberg-spark  Removed                                                                                                                                                        0.0s 
 ✔ Container pyiceberg-rest   Removed                                                                                                                                                        0.0s 
 ✔ Container pyiceberg-mc     Removed                                                                                                                                                        0.0s 
 ✔ Container hive             Removed                                                                                                                                                        0.0s 
docker compose -f dev/docker-compose-integration.yml up -d
WARN[0000] /home/jeffrey/Desktop/GItHub_Project/iceberg-python/dev/docker-compose-integration.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 5/5
 ✔ Container pyiceberg-minio  Started                                                                                                                                                        0.5s 
 ✔ Container hive             Started                                                                                                                                                        0.4s 
 ✔ Container pyiceberg-rest   Started                                                                                                                                                        0.7s 
 ✔ Container pyiceberg-mc     Started                                                                                                                                                        0.9s 
 ✔ Container pyiceberg-spark  Started                                                                                                                                                        1.0s 
sleep 10
docker compose -f dev/docker-compose-integration.yml cp ./dev/provision.py spark-iceberg:/opt/spark/provision.py
WARN[0000] /home/jeffrey/Desktop/GItHub_Project/iceberg-python/dev/docker-compose-integration.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Copying 1/0
 ✔ pyiceberg-spark copy ./dev/provision.py to pyiceberg-spark:/opt/spark/provision.py Copied                                                                                                 0.0s 
docker compose -f dev/docker-compose-integration.yml exec -T spark-iceberg ipython ./provision.py
WARN[0000] /home/jeffrey/Desktop/GItHub_Project/iceberg-python/dev/docker-compose-integration.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
24/09/18 11:02:25 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Could not initialize FileIO: pyiceberg.io.pyarrow.PyArrowFileIO
Could not initialize FileIO: pyiceberg.io.pyarrow.PyArrowFileIO                 
Could not initialize FileIO: pyiceberg.io.pyarrow.PyArrowFileIO
Could not initialize FileIO: pyiceberg.io.pyarrow.PyArrowFileIO
poetry run pytest tests/ -v -m integration 

====================================================================================== test session starts =======================================================================================
platform linux -- Python 3.11.9, pytest-7.4.4, pluggy-1.5.0 -- /home/jeffrey/Desktop/GItHub_Project/iceberg-python/venv/bin/python
cachedir: .pytest_cache
rootdir: /home/jeffrey/Desktop/GItHub_Project/iceberg-python
configfile: pyproject.toml
plugins: lazy-fixture-0.6.3, mock-3.14.0, requests-mock-1.12.1, checkdocs-2.10.1
collected 3640 items / 2840 deselected / 800 selected 

... tests ...
====================================================== 501 passed, 7 skipped, 2840 deselected, 731 warnings, 292 errors in 99.24s (0:01:39) ======================================================
```

</details>

**Comment by sungwy** [comment]
> Log of make test-integration on my VM has so many errors. Any ideas? (It succeeds on CI Test).

What kind of errors are you running into @JE-Chen ? Could you provide us an example?

**Review by sungwy — APPROVED** [review]

**Comment by JE-Chen** [comment]
* Open Pycharm
* Open iceberg project 
* Create new venv using python 3.11.9
* pip install poetry
* make install 
* make test-integration
* Get this message four time `Could not initialize FileIO: pyiceberg.io.pyarrow.PyArrowFileIO`
* Start run tests and get so many error (501 passed, 7 skipped, 2840 deselected, 731 warnings, 292 errors in 99.24s (0:01:39))

**Comment by sungwy** [comment]
Thank you for sending over the reproducible steps @JE-Chen - I do not use PyCharm for my development (I'm a VSCode user) so it might take a while for me to reproduce your setup.

`Could not initialize FileIO: pyiceberg.io.pyarrow.PyArrowFileIO`

https://github.com/apache/iceberg-python/blob/de47590c6ac4f507cb2337c20504a62c484339f9/pyiceberg/io/__init__.py#L320-L322

This is a warning message and I'm familiar with seeing that in my integration tests as well, but it didn't result in any of the tests failing in my case. Are you able to share the verbose error trace for a failing test case, so we can investigate what its failing on?

**Comment by JE-Chen** [comment]
Look like all error cause by: `pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.`

There are full log.
[[test.log](https://github.com/user-attachments/files/17045582/test.log)](https://gist.github.com/JE-Chen/d29aa4ab86d256cfe79788157ff83983)

**Comment by kevinjqliu** [comment]
```
	Suppressed: org.apache.spark.util.TaskCompletionListenerException: Memory was leaked by query. Memory leaked: (3227648)
Allocator(toArrowBatchIterator) 0/3227648/3227648/9223372036854775807 (res/actual/peak/limit)
```

What VM are you running the integration tests on? 

I have a theory that a previous change is causing memory leaks (see #1167). Can you try to revert it and run the integration test? 
https://github.com/apache/iceberg-python/commit/1971fcfe0875eeb200dbcb66f385e504cfad6609
```
git revert 1971fcfe0875eeb200dbcb66f385e504cfad6609
```

**Comment by JE-Chen** [comment]
> ```
> 	Suppressed: org.apache.spark.util.TaskCompletionListenerException: Memory was leaked by query. Memory leaked: (3227648)
> Allocator(toArrowBatchIterator) 0/3227648/3227648/9223372036854775807 (res/actual/peak/limit)
> ```
> 
> What VM are you running the integration tests on?
> 
> I have a theory that a previous change is causing memory leaks (see #1167). Can you try to revert it and run the integration test? [1971fcf](https://github.com/apache/iceberg-python/commit/1971fcfe0875eeb200dbcb66f385e504cfad6609)
> 
> ```
> git revert 1971fcfe0875eeb200dbcb66f385e504cfad6609
> ```

VMware Workstation 17 pro with these setting:
image

**Comment by kevinjqliu** [comment]
Gotcha, thanks! I think the CI runs in ubuntu, so it should mirror your own setup

**Comment by kevinjqliu** [comment]
seems like its an issue with your docker installation. 

https://github.com/apache/iceberg-python/blob/41a3c8ea4e9c3592331755970bfc38f52eaf3fd8/dev/docker-compose-integration.yml#L21

here's what I found for "VMware Workstation 17 Pro "
https://www.reddit.com/r/vmware/comments/167rurt/easy_way_to_run_docker_container_in_vmware/

**Comment by JE-Chen** [comment]
My Windows environment has the same pull issue.
{ADD7151F-C1E1-48BE-96AB-F1575E271E57}

**Comment by kevinjqliu** [comment]
@JE-Chen I was able to run integration tests for this PR locally. And given that CI also pass, let's merge this and debug your VM environment issue separately. 
How does that sound?

**Comment by JE-Chen** [comment]
> @JE-Chen I was able to run integration tests for this PR locally. And given that CI also pass, let's merge this and debug your VM environment issue separately. How does that sound?

Sounds great.

**Review by kevinjqliu — APPROVED** [review]
LGTM, confirmed no more warnings

**Comment by kevinjqliu** [comment]
Thank you @JE-Chen for the contribution and @sungwy for the review

**Pull request merged**
