### PR TITLE
[Bug Fix] all TimeTransforms for falsey values 

### PR DESCRIPTION
**Pull request by syun64**
Following up on @HonahX 's comment on https://github.com/apache/iceberg-python/pull/276

### CODE REVIEW

**Review by Fokko — APPROVED** [review]
Ah, this also got me more than once 😄

**Comment by syun64** [comment]
CI failure related to: https://github.com/apache/iceberg-python/pull/279

**Comment by Fokko** [comment]
@syun64 Thanks, let me poke someone to get it in 👍

**Comment by syun64** [comment]
No problem, and thank you! :)

**Comment by Fokko** [comment]
@syun64 The other PR is in 👍 Can you rebase?

**Comment by syun64** [comment]
of course!

**Review by HonahX — APPROVED** [review]
LGTM! Thanks for the quick fix.

**Comment by syun64** [comment]
Thank you for the reviews @Fokko @HonahX . Could I ask for your help in merging it in? :)

**Comment by HonahX** [comment]
@syun64 Sorry I was interrupted by other things. Merging!

**Pull request merged**
