### PR TITLE
[CI FIx] Use Docker Compose V2

### LINKED ISSUE #574: GitHub Workflows Fail because Docker Compose v1 support is removed
### Apache Iceberg version

main (development)

### Please describe the bug 🐞

https://github.com/actions/runner-images/issues/9557

We need to update the MakeFile to use `docker compose` instead.

### PR DESCRIPTION
**Pull request by HonahX**
Fixes #574

### CODE REVIEW

**Review by Fokko — APPROVED** [review]
I was looking into this as well :D Thanks for the quick turnaround!

**Comment by Fokko** [comment]
@HonahX Seem to be a few more in `./dev/run-{azurite,gcs-server,minio}.sh`

**Comment by HonahX** [comment]
@Fokko Thanks for the quick review! I updated all remaining `docker-compose` to `docker compose`

**Comment by Fokko** [comment]
Thank you for the PR @HonahX  🚀

**Pull request merged**
