### PR TITLE
Make scope configurable

### PR DESCRIPTION
**Pull request by himadripal**
#462

### CODE REVIEW

**Review by Fokko — COMMENTED** [review]
Thanks for working on this @himadripal. Can you fix the conflicts? Thanks!

**Review by Fokko — APPROVED** [review]

**Comment by himadripal** [comment]
@Fokko Thank you for the approval.  Fixed the conflict, can you please let the build checks run?

**Comment by Fokko** [comment]
The easiest way is to fix this locally using `make install && make lint`

**Comment by himadripal** [comment]
> The easiest way is to fix this locally using `make install && make lint`

@Fokko  Thank you for this tip.

**Comment by himadripal** [comment]
locally all passed
```shell
(venv) hpal@HPals-MacBook-ProM1 apache-iceberg-python % poetry run pre-commit run --all-files
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check docstring is first.................................................Passed
debug statements (python)................................................Passed
check yaml...............................................................Passed
check python ast.........................................................Passed
ruff.....................................................................Passed
ruff-format..............................................................Passed
mypy.....................................................................Passed
pycln....................................................................Passed
mdformat.................................................................Passed
pydocstyle...............................................................Passed
flynt....................................................................Passed
```
can someone rerun the build check?

**Review by Fokko — APPROVED** [review]
Looks good. Could you also create a PR to update the documentation: https://github.com/apache/iceberg-python/blob/36b56eb7bbc4cff91e4b9bfdf71ca0a7b8bbee5c/mkdocs/docs/configuration.md?plain=1#L152

**Review by flyrain — APPROVED** [review]
+1 thanks @himadripal for working on it.

**Review by Fokko — APPROVED** [review]

**Comment by Fokko** [comment]
Thanks for working on this @himadripal and for the review @flyrain

**Pull request merged**
