### PR TITLE
feat: Implement list_views Method and __is_view Utility Function

### PR DESCRIPTION
**Pull request by omkenge**
- Implemented the `list_views` method to retrieve a list of views from the specified Glue database.
- Added a utility method `__is_view` to check if a table is a view based on its metadata.

The new functionality enhances the usability of the Glue catalog by allowing users to easily retrieve views, improving data management and accessibility.
Hello team ( @sungwy @kevinjqliu ) Could you plz check this PR
Thank You

### CODE REVIEW

**Comment by omkenge** [comment]
I successfully tested the code works fine for me ..

**Comment by sungwy** [comment]
Hi @omkenge - thank you for working on this PR. Could we add a test to: https://github.com/apache/iceberg-python/blob/main/tests/catalog/test_glue.py so we can verify the API in our CI?

**Comment by kevinjqliu** [comment]
on testing, it would be great to include an integration test with a Spark Iceberg view

**Comment by omkenge** [comment]
HI @sungwy , I added test for list view you can verify
and answer to @kevinjqliu, sure I will work on your suggestion

**Comment by omkenge** [comment]
Hello @kevinjqliu , 
Could you plz elaborate on this why we need this and what's your thinking ?
From my understanding ,It is integration of Iceberg tables (or views) within the Glue Catalog when working with Spark
Is it right ?

**Comment by kevinjqliu** [comment]
Sorry about the confusion, I didn't see that this PR is specific to glue. My comment on the integration test is for adding iceberg views in general. I don't think we have sufficient test coverage for iceberg views.

**Comment by kevinjqliu** [comment]
Does AWS glue catalog currently support Iceberg view? I could not find any documentation on iceberg view support. On the Java side, GlueCatalog does not current support Iceberg view https://github.com/apache/iceberg/blob/6b04a6d000019a6182eb6521d1e7e4124a0cd73b/aws/src/main/java/org/apache/iceberg/aws/glue/GlueCatalog.java#L83-L84

HiveCatalog on the other hand supports iceberg views (extends `BaseMetastoreViewCatalog`)
https://github.com/apache/iceberg/blob/6b04a6d000019a6182eb6521d1e7e4124a0cd73b/hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java#L75-L76

**Comment by omkenge** [comment]
Hi @kevinjqliu ,
You are correct that AWS Glue is not support Iceberg View.
It's feasible to implement a list_views function in PyIceberg with the AWS Glue Catalog, even though Glue itself doesn't natively support Iceberg views. This approach would let you retrieve and manage view metadata directly via PyIceberg, keeping it in sync with your SQL-created views without Glue needing built-in view support. It’s a practical solution to integrate your existing views and access them through PyIceberg in your AWS environment.

**Comment by omkenge** [comment]
HI @kevinjqliu ,
You are right .. So no need to add the list_view for aws glue catalog
But can I work on Hive Catalog get_views method ?

**Comment by omkenge** [comment]
Hello Team lets closed this PR ,I will add list_view for hive catalog in new PR

**Pull request closed without merging**
