### PR TITLE
Python: Add support for Python 3.12

### PR DESCRIPTION
**Pull request by steinsgateted**
reopen the PR: [Python: Add support for Python 3.12](https://github.com/apache/iceberg/pull/8531)

### CODE REVIEW

**Comment by Fokko** [comment]
Thanks for opening this PR. 3.12 has been released today: https://www.python.org/downloads/release/python-3120/

**Comment by Fokko** [comment]
@steinsgateted can you pull in the main branch? It looks like that 3.12 is available: https://github.com/actions/python-versions/releases

**Comment by steinsgateted** [comment]
@Fokko Thank you.
Encountered this problem:

> Note: This error originates from the build backend, and is likely not a problem with poetry but with aiohttp (3.8.5) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "aiohttp (==3.8.5)"'.

**Comment by jayceslesar** [comment]
@steinsgateted looks like there are no 3.12 wheels yet see the discussion on https://github.com/aio-libs/aiohttp/issues/7639

**Comment by steinsgateted** [comment]
@jayceslesar Thank you for the information

**Comment by Fokko** [comment]
Thanks for picking this up again, it looks like it is now blocked on Poetry: https://github.com/apache/iceberg-python/pull/158

**Comment by steinsgateted** [comment]
@Fokko @jayceslesar Thank you

> @steinsgateted looks like there are no 3.12 wheels yet see the discussion on https://github.com/aio-libs/aiohttp/issues/7639

I found that `3.9.0b0` supports python3.9.
Do we change 3.8.6 to 3.9?

**Comment by MehulBatra** [comment]
Looking into this

**Comment by Fokko** [comment]
@steinsgateted can you rebase the PR?

**Comment by kevinjqliu** [comment]
Closing this in favor of #1068

**Pull request closed without merging**
