### PR TITLE
added contributing.md file

### PR DESCRIPTION
**Pull request by onemriganka**
fixes / #101 
HEY, I HAVE ADDED A SIMPLE CONTRIBUTING.MD FILE. HOPE IT WILL HELP BEGINEERS

### CODE REVIEW

**Comment by Fokko** [comment]
@onemriganka What do you think of pointing to https://py.iceberg.apache.org/contributing/? Otherwise we have to maintain this at two places

**Comment by onemriganka** [comment]
> @onemriganka What do you think of pointing to https://py.iceberg.apache.org/contributing/? Otherwise we have to maintain this at two places

YES ,https://py.iceberg.apache.org/contributing/ <- this is great .But i think as begineers only find usefull files like README.md etc only in github. so when we have contributing.md file in the repo will be easy for begineer  to understand and contribute. professionals check website of the project but many begineer do not

**Comment by Fokko** [comment]
But what are your thoughts on linking from the `CONTRIBUTING.md` to the website? Otherwise, it is abound to get out of sync.

**Comment by onemriganka** [comment]
OK sir, if you think the website is more helpful then ok... Thanks

**Pull request closed without merging**
