### PR TITLE
feat: Add support for YYYYMMDD date formats

### PR DESCRIPTION
**Pull request by omkenge**
#### Summary
This PR extends the date/time handling functions by adding support for one additional formats:
- `YYYYMMDD` (e.g., `20241018`)

#### Changes
- Updated the `date_str_to_days` function to handle the `YYYYMMDD` date format
- Added corresponding regex patterns to match these formats.

Please @kevinjqliu reviewthis and provide feedback!

### CODE REVIEW

**Comment by kevinjqliu** [comment]
hey @omkenge, thanks for the PR. What use case is this for?

**Comment by omkenge** [comment]
Hey @kevinjqliu sorry for the late reply ...
So talking about use cases ..
Many legacy systems and industries (e.g., government sectors) store dates in compact YYYYMMDD format. 
Supporting YYYYMMDD allows developers to work seamlessly with historical datasets without needing to pre-process them.
As I am working in a Mechatronics company, the YYYYMMDD format is crucial for handling machine-generated data in areas such as maintenance schedules, log entries, and component tracking.

**Comment by kevinjqliu** [comment]
Thanks for the context! 

My opinion is that it's best not to add the `YYYYMMDD` format to the pyiceberg library. Here are my reasoning.
- I think date parsing can be done outside of the pyiceberg library. For example, we can transform date strings from `YYYYMMDD` to the currently supported ISO-8601 format (`YYYY-MM-DD`).
- Supporting yet another date string format adds more complexity. If we support `YYYYMMDD`, why not also support `MMDDYYYY`? 

I think its best to only support ISO-8601 (`YYYY-MM-DD`) in the pyiceberg library and have other date strings transform to this format. 

What do you think?

**Comment by omkenge** [comment]
Thank you for your feedback! I understand your concerns.
Ok then lets keep it simple and we can closed this PR with your final comment ...

**Comment by omkenge** [comment]
and also i have some suggestions on other parts also , i will create PR as soon as possible 
Plz also share your thoughts on that part also
Thank you for your time

**Comment by kevinjqliu** [comment]
@omkenge do you mind creating an issue first? We can have a discussion and allow others to chime in before starting the PR

**Pull request closed without merging**
